---
- name: Discover Docker Swarm manager
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - docker-swarm-manager


- name: Docker Stack Status
  hosts: all
  gather_facts: false

  roles:
    - docker-stack-status