all:
  children:
    docker:
      children:

        # Environment
        development:
          hosts:
            shack-app-d001:
              ansible_host: 10.0.0.31
              docker_swarm_bootstrap: true
            shack-app-d002:
              ansible_host: 10.0.0.32
            shack-app-d003:
              ansible_host: 10.0.0.33
            shack-app-d004:
              ansible_host: 10.0.0.34


        # Role
        managers:
          hosts:
            shack-app-d001:
            shack-app-d002:
            shack-app-d003:
            shack-app-d004:

        # workers:
