---
- name: Find secret templates
  find:
    paths: "{{ stack_path }}/secrets"
    patterns: "*.j2"
  register: secret_templates

- name: Create temporary secret directory
  file:
    path: "/tmp/{{ stack_name }}-secrets"
    state: directory
    mode: "0700"

- name: Render secret templates
  template:
    src: "{{ item.path }}"
    dest: "/tmp/{{ stack_name }}-secrets/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    mode: "0600"
  loop: "{{ secret_templates.files }}"

- name: Create docker secrets
  community.docker.docker_secret:
    name: "{{ stack_name }}_{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    data_src: "/tmp/{{ stack_name }}-secrets/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    state: present
  loop: "{{ secret_templates.files }}"

- name: Remove temporary secrets
  file:
    path: "/tmp/{{ stack_name }}-secrets"
    state: absent
