---
docker_services_repo: "git@github.com:shackofnoreturn/shackhq-docker-stacks.git"

docker_services_root: /opt/docker

docker_services_branch_map:
  production: production
  testing: testing
  development: development
  management: production
