---
# - name: Stack list
#   command:
#     cmd: docker stack ls
#   register: stack_list

- name: Show stack list
  community.docker.docker_stack_info:
  delegate_to: "{{ docker_deploy_manager }}"
  register: docker_stack_list


# - name: Stack services
#   command:
#     cmd: docker stack services {{ stack_name }}
#   register: stack_services

- name: Show stack services
  community.docker.docker_swarm_service_info:
    name: "{{ stack_name }}"
  delegate_to: "{{ docker_deploy_manager }}"
  register: stack_services


- name: Display stack status
  ansible.builtin.debug:
    msg:
      - "========================================"
      - "Environment: {{ docker_environment }}"
      - "Manager:    {{ docker_deploy_manager }}"
      - "Stack:      {{ stack_name }}"
      - "========================================"
      - ""
      - "Docker stacks:"
      - "{{ docker_stack_list.stdout }}"
      - ""
      - "Stack services:"
      - "{{ docker_stack_services.stdout }}"
  run_once: true
