---
- name: Stack list
  command:
    cmd: docker stack ls
  register: stack_list


- name: Stack services
  command:
    cmd: docker stack services {{ stack_name }}
  register: stack_services


- name: Display stack status
  debug:
    msg:
      - "{{ stack_list.stdout_lines }}"
      - "{{ stack_services.stdout_lines }}"
