---
- name: Determine manager candidates
  ansible.builtin.set_fact:
    docker_swarm_manager_candidates: >-
      {{
        groups['managers']
        | intersect(groups[docker_environment])
      }}
  run_once: true

- name: Validate manager candidates
  ansible.builtin.assert:
    that:
      - docker_swarm_manager_candidates | length > 0
    fail_msg: >-
      No manager candidates found for environment
      '{{ docker_environment }}'.
  run_once: true

- name: Check manager candidates
  ansible.builtin.include_tasks:
    file: discover.yml
  when:
    - inventory_hostname in docker_swarm_manager_candidates

- name: Build reachable manager list
  ansible.builtin.set_fact:
    docker_available_managers: >-
      {{
        docker_swarm_manager_candidates
        | select('in', ansible_play_hosts)
        | select('match', '.*')
        | list
      }}
  run_once: true