---
- name: Ensure git installed
  apt:
    name: git
    state: present
    update_cache: true

- name: Ensure services directory exists
  file:
    path: "{{ docker_services_root }}"
    state: directory
    mode: "0755"

- name: Set deploy key path
  set_fact:
    docker_git_ssh_key_path: "/tmp/docker_services_deploy_key_{{ ansible_date_time.epoch }}"

- block:
    - name: Write deploy key to disk
      copy:
        content: "{{ docker_stacks_deploy_key }}"
        dest: "{{ docker_git_ssh_key_path }}"
        mode: "0600"
      no_log: true

    - name: Clone repository
      git:
        repo: "{{ docker_services_repo }}"
        dest: "{{ docker_services_root }}"
        version: "{{ docker_git_branch }}"
        force: true
        accept_hostkey: true
        key_file: "{{ docker_git_ssh_key_path }}"
  always:
    - name: Remove deploy key from disk
      file:
        path: "{{ docker_git_ssh_key_path }}"
        state: absent


- name: Clone repository
  git:
    repo: "{{ docker_services_repo }}"
    dest: "{{ docker_services_root }}"
    version: "{{ docker_git_branch }}"
    force: true
    accept_hostkey: true
    key_file: "{{ docker_stacks_deploy_key }}"

- name: Determine current commit
  command:
    cmd: git rev-parse HEAD
    chdir: "{{ docker_services_root }}"
  register: git_commit
  changed_when: false

- name: Show synchronized commit
  debug:
    msg:
      - "Environment : {{ docker_environment }}"
      - "Branch      : {{ docker_git_branch }}"
      - "Commit      : {{ git_commit.stdout }}"
